ccflags-y += -march=armv8.2-a+crypto+rcpc+dotprod -mtune=cortex-a78 -mtune=cortex-a55 -flto=thin -funroll-loops -ftree-vectorize -Ofast

obj-$(CONFIG_OPLUS_FEATURE_CPUFREQ_BOUNCING) += cpufreq_bouncing.o
