/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

#define LOAD_AVG_PERIOD 16
#define LOAD_AVG_MAX 24130
#define PELT32_LOAD_AVG_PERIOD 32
#define PELT32_LOAD_AVG_MAX 47742

static const u32 runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff, 0xf5257d14, 0xeac0c6e6, 0xe0ccdeeb, 0xd744fcc9, 0xce248c14,
	0xc5672a10, 0xbd08a39e, 0xb504f333, 0xad583ee9, 0xa5fed6a9, 0x9ef5325f,
	0x9837f050, 0x91c3d373, 0x8b95c1e3, 0x85aac367,
};

#define PELT16_LOAD_AVG_PERIOD 16
#define PELT16_LOAD_AVG_MAX 24130

static const u32 pelt8_runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff, 0xeac0c6e6, 0xd744fcc9, 0xc5672a10,
	0xb504f333, 0xa5fed6a9, 0x9837f050, 0x8b95c1e3,
};

#define PELT8_LOAD_AVG_PERIOD 8
#define PELT8_LOAD_AVG_MAX 12336

extern const u32 *pelt_runnable_avg_yN_inv;
extern int pelt_load_avg_period;
extern int pelt_load_avg_max;

#define LOAD_AVG_PERIOD pelt_load_avg_period
#define LOAD_AVG_MAX pelt_load_avg_max
