# SPDX-License-Identifier: GPL-2.0-only
TECHPACK?=y

subdir-ccflags-y += -mcpu=kryo -march=armv8-a+crypto+rcpc+dotprod+fp16+aes+sha2+lse+simd+sve2  \
		 -mcpu=cortex-a78 -mtune=cortex-a78  \
		 -funroll-loops -ftree-vectorize \
		 -mfpu=neon-fp-armv8 -mfloat-abi=hard \
		 -msve-vector-bits=128 -fno-common

techpack-dirs := $(shell find $(srctree)/techpack -maxdepth 1 -mindepth 1 -type d -not -name ".*")
obj-${TECHPACK} += stub/ $(addsuffix /,$(subst $(srctree)/techpack/,,$(techpack-dirs)))
