# Snapdragon optimization
KBUILD_CFLAGS  +=  -fno-rtti
KBUILD_CFLAGS  +=  -fno-trapping-math
KBUILD_CFLAGS  +=  -fno-exceptions
KBUILD_CFLAGS  +=  -fno-math-errno

obj-$(CONFIG_LZ4KD_COMPRESS) += lz4kd_encode.o
obj-$(CONFIG_LZ4KD_DECOMPRESS) += lz4kd_decode.o
